[build]
  # Build command for Next.js
  command = "npm run build"
  
  # Next Runtime handles publishing/functions automatically for Next.js
  # Remove manual publish and functions to avoid conflicts

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # Next.js specific environment variables
  NEXT_TELEMETRY_DISABLED = "1"

# Do NOT add a SPA catch-all redirect; Next Runtime must serve API and SSR routes

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Image optimization
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"
